# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Python test env
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install poetry
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --user pipx
        pipx install poetry
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install dependencies
      run: |
        poetry install
        
    - name: Test with pytest
      run: |
        poetry run pytest
